#!/bin/bash
# ============================================================================
# Dream Claude Research — New Paper Initializer
# Creates a ready-to-use paper project with all skills pre-installed.
#
# Usage:
#   ./init-paper.sh <project-name>
#   ./init-paper.sh my-cardiac-ct-paper
#
# What it does:
#   1. Creates the project directory with the standard structure
#   2. Copies all Dream skills into .claude/skills/
#   3. Creates a manuscript.md template with YAML front matter
#   4. Initializes a Git repository
#   5. Prints next steps
# ============================================================================

set -e

# --- Configuration ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILLS_SOURCE="$SCRIPT_DIR/skills"

# --- Validate ---
if [ -z "$1" ]; then
    echo ""
    echo "  Dream Claude Research — New Paper Initializer"
    echo "  ============================================="
    echo ""
    echo "  Usage:  ./init-paper.sh <project-name>"
    echo ""
    echo "  Example:"
    echo "    ./init-paper.sh my-cardiac-ct-paper"
    echo ""
    exit 1
fi

PROJECT_NAME="$1"
PROJECT_DIR="$(pwd)/$PROJECT_NAME"

if [ -d "$PROJECT_DIR" ]; then
    echo "Error: Directory '$PROJECT_NAME' already exists."
    exit 1
fi

if [ ! -d "$SKILLS_SOURCE" ]; then
    echo "Error: Skills folder not found at '$SKILLS_SOURCE'."
    echo "Make sure you're running this from the dream-Claude-Research directory."
    exit 1
fi

# --- Create project structure ---
echo ""
echo "Creating project: $PROJECT_NAME"
echo "──────────────────────────────────────"

mkdir -p "$PROJECT_DIR"/{papers,figures,notes,data,styles,.claude/skills}

echo "  Created project directories"

# --- Copy skills ---
cp -r "$SKILLS_SOURCE"/* "$PROJECT_DIR/.claude/skills/"
echo "  Installed $(ls "$PROJECT_DIR/.claude/skills/" | wc -l | tr -d ' ') Dream skills"

# --- Create manuscript template ---
cat > "$PROJECT_DIR/manuscript.md" << 'MANUSCRIPT'
---
title: "Your Paper Title"
author:
  - name: First Author
    affiliation: University of Bern
    email: first@example.com
  - name: Second Author
    affiliation: Partner Institution
bibliography: references.json
csl: styles/your-journal.csl
---

# Abstract

<!-- Write last. 250 words max for most journals. -->

# Introduction

<!-- Phase 6: Use scientific-writing skill. Build the narrative arc. -->

# Methods

<!-- Be precise enough for replication. -->

# Results

<!-- State findings. No interpretation here. -->

# Discussion

<!-- Interpret results. Compare to literature. -->

## Limitations

<!-- Be honest. Reviewers will find them anyway. -->

# Conclusion

<!-- 1 paragraph. What did you find, why does it matter. -->

# Statements

## Conflicts of Interest

The authors declare no conflicts of interest.

## Acknowledgments

<!-- People, funding, compute resources. -->

## Data Availability

<!-- Where can others find your data? -->

# References

<!-- Auto-generated by Pandoc from [@citekeys] in the text. -->

---

# Supplementary Materials

## Supplementary Figures

## Supplementary Tables

## Supplementary Notes
MANUSCRIPT

echo "  Created manuscript.md template"

# --- Create .gitignore ---
cat > "$PROJECT_DIR/.gitignore" << 'GITIGNORE'
# OS
.DS_Store
Thumbs.db

# Editors
.vscode/settings.json
*.swp
*~

# Build outputs
*.docx
*.pdf
!papers/*.pdf

# Large files (use Git LFS or keep locally)
# papers/*.pdf
GITIGNORE

echo "  Created .gitignore"

# --- Create VS Code settings for Pandoc ---
mkdir -p "$PROJECT_DIR/.vscode"
cat > "$PROJECT_DIR/.vscode/settings.json" << 'VSCODE'
{
  "pandoc.docxOptString": "--citeproc --bibliography=references.json --csl=styles/your-journal.csl",
  "pandoc.pdfOptString": "--citeproc --bibliography=references.json --csl=styles/your-journal.csl",
  "files.associations": {
    "*.md": "markdown"
  }
}
VSCODE

echo "  Created VS Code settings"

# --- Initialize Git ---
cd "$PROJECT_DIR"
git init --quiet
git add -A
git commit --quiet -m "Initial project setup with Dream Claude Research skills"

echo "  Initialized Git repository"

# --- Done ---
echo ""
echo "Done! Your project is ready at:"
echo "  $PROJECT_DIR"
echo ""
echo "Project structure:"
echo "  $PROJECT_NAME/"
echo "  ├── .claude/skills/     ← 12 Dream skills (auto-detected by Cowork)"
echo "  ├── .vscode/            ← Pandoc export settings"
echo "  ├── papers/             ← Drop your PDFs here"
echo "  ├── figures/            ← Generated figures"
echo "  ├── notes/              ← CrystaLit notes (one per paper)"
echo "  ├── data/               ← CrystaLit aggregated data"
echo "  ├── styles/             ← Put your .csl journal style here"
echo "  ├── manuscript.md       ← Your paper"
echo "  └── .gitignore"
echo ""
echo "Next steps:"
echo "  1. cd $PROJECT_NAME"
echo "  2. Export your Zotero collection as Better CSL JSON → references.json"
echo "  3. Download your journal's .csl file → styles/"
echo "  4. Drop your PDFs into papers/"
echo "  5. Open in Claude Cowork (select this folder) and say:"
echo "     'Run Foundation Scout' to start Phase 1"
echo ""
